version: '3'
services:
  cli:
    build:
      context: .
    container_name: cli
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: bash
    # network_mode cannot be combined with networks: or ports: options in the same container.
    network_mode: host
